### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CarbonSheild** [martindmtrv/Carleton-Schedule-Grabber#1]
Shell output:

============ RESTART: C:\Users\carbo\Desktop\New folder\Carleton-Schedule-Grabber-master\main.py ============
Sign in in the browser!
Found schedule.html press enter to start!
Traceback (most recent call last):
  File "C:\Users\carbo\Desktop\New folder\Carleton-Schedule-Grabber-master\main.py", line 278, in <module>
    main()
  File "C:\Users\carbo\Desktop\New folder\Carleton-Schedule-Grabber-master\main.py", line 262, in main
    timeTable = infoGrabber()
  File "C:\Users\carbo\Desktop\New folder\Carleton-Schedule-Grabber-master\main.py", line 162, in infoGrabber
    if table[9] == 'Video on Demand':
IndexError: list index out of range
>>>

**Comment by CarbonSheild** [comment]
I think they may have changed the formating of the site, here is an current example : 

<table class="datadisplaytable" summary="This table lists the scheduled meeting times and assigned instructors for this class.."><caption class="captiontext">Scheduled Meeting Times</caption>
<tbody><tr>
<th class="ddheader" scope="col">Type</th>
<th class="ddheader" scope="col">Time</th>
<th class="ddheader" scope="col">Days</th>
<th class="ddheader" scope="col">Where</th>
<th class="ddheader" scope="col">Date Range</th>
<th class="ddheader" scope="col">Schedule Type</th>
<th class="ddheader" scope="col">Instructors</th>
</tr>
<tr>
<td class="dddefault">Class</td>
<td class="dddefault">4:05 pm - 5:25 pm</td>
<td class="dddefault">TR</td>
<td class="dddefault"><abbr title="To Be Announced">TBA</abbr></td>
<td class="dddefault">Sep 09, 2020 - Oct 23, 2020</td>
<td class="dddefault">Lecture</td>
<td class="dddefault">Cheryl Joanne  Schramm (<abbr title="Primary">P</abbr>)</td>
</tr>
</tbody></table>
<br>
<table class="datadisplaytable" summary="This layout table is used to present the schedule course detail">
<tbody><tr><th colspan="3" class="ddtitle" scope="colgroup"><a href="http://culearn.carleton.ca/" onmouseover="window.status=&#39;http://culearn.carleton.ca/&#39;;  return true" onfocus="window.status=&#39;http://culearn.carleton.ca/&#39;;  return true" onmouseout="window.status=&#39;&#39;;  return true" onblur="window.status=&#39;&#39;;  return true">Circuits - ECOR 1043 - 3A</a></th>
</tr><tr>
<th colspan="2" class="ddlabel" scope="row">Associated Term:</th>
<td class="dddefault">Fall 2020 (September-December)</td>
